name: Testingos

on: [push, pull_request]

jobs:
  test:
    name: Python Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "DB_LOGIN=${{ secrets.DB_LOGIN }}" >> .env
          echo "KEY=${{ secrets.KEY }}" >> .env

      - name: Run ATS
        uses: codecov/codecov-ats@v0
        env:
          CODECOV_STATIC_TOKEN: ${{ secrets.CODECOV_STATIC_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Run tests and collect coverage
        run: pytest --cov app ${{ env.CODECOV_ATS_TESTS }}
     
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          flags: smart-tests
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
